{{- if eq .Values.deploymentStrategy "canary" }}

apiVersion: apps/v1

kind: Deployment

metadata:
   name: "frontend-canary"
   namespace: {{ .Values.namespace }}
   labels: 
    app: "frontend-canary-label"

spec:

    replicas: {{ .Values.frontend.canary.replicaCount }}

    selector:
     matchLabels:
       app: "frontend-canary-label"

    template:
      
     metadata:
      labels:
       app: "frontend-canary-label"

     spec:
        containers:
        - name: "frontend-canary-container"
          image: "{{ .Values.frontend.canary.image.repository }}:{{ .Values.frontend.canary.image.tag }}"
          ports:
          - containerPort: 3000

          resources:
           requests:
             cpu: "200m"
             memory: "500Mi"
           limits:
             cpu: "500m"
             memory: "1Gi"
        
          readinessProbe:
           httpGet:
              path: /
              port: 3000

           initialDelaySeconds: 20
           periodSeconds: 15

           successThreshold: 1
           timeoutSeconds: 5
           failureThreshold: 3

          livenessProbe:
           httpGet:
              path: /
              port: 3000
           initialDelaySeconds: 20
           periodSeconds: 15

           successThreshold: 1
           timeoutSeconds: 5
           failureThreshold: 3

          env:
           - name: "MYDATABASE"
             valueFrom:
              secretKeyRef:
               name: "backend-secrets-canary-stable"
               key: MYDATABASE
         
{{- end }}