{{- if eq .Values.deploymentStrategy "canary" }}

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
 name: "frontend-stable-ingress"
 namespace: {{ .Values.namespace }}

spec:
   ingressClassName: nginx

   rules:
 
   - host: stage-canary.internal
     http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
         service:
           name: "frontend-stable-service"
           port:
            number: 80

{{- end }}