sonar.projectKey=Production-Grade-DevSecOps-Platform
sonar.projectName=Production-Grade-DevSecOps-Platform
sonar.sources=frontend,backend
sonar.projectVersion=1.0  # this is the current project version 1.0 and sonarqube can test it like version 1.0 has bugs or not.
sonar.exclusions=**/node_modules/**
sonar.sourceEncoding=UTF-8 # Read my source files using UTF-8 character encoding. Without this sonar can read the garbage values.
