apiVersion: v1
kind: Namespace
metadata:
  name: "dev-rolling-update"

---

apiVersion: v1
kind: Namespace
metadata:
  name: "stage-canary"

---

apiVersion: v1
kind: Namespace
metadata:
  name: "prod-blue-green"