apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-local

  hostPath:
    path: /home/harshv/Desktop/TF-AWS-Automation-Project/portfolio-website/monitoring/grafana/grafana-storage

