apiVersion: v1

kind: Service

metadata:
   name: "blue-green-backend-service"
   namespace: "prod-blue-green"
spec:  
   
   selector: 
    app: backend-green-deployment-label
    version: green

   ports:
     - protocol: TCP
       port: 80
       targetPort: 5000

   type: ClusterIP
   

   