apiVersion: apps/v1

kind: Deployment

metadata:
  name: "backend-canary"
  namespace: "stage-canary"
  labels: 
    app: "backend-canary-label"

spec:
  
  replicas: 1

  selector:
   matchLabels:
    app: "backend-canary-label"

  template:
     
     metadata:
       labels: 
          app: "backend-canary-label"

     spec:
       containers:
        - name: "backend-canary-container"
          image: harshvrm10/portfolio-app-repo:portfolio-app-backend-v10
          ports:
           - containerPort: 5000

          resources:
           requests:
            cpu: "200m"
            memory: "500Mi" 

           limits:
            cpu: "500m"
            memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15

            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
           
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15

            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3

          env:
           - name: "PORT"
             valueFrom:
              configMapKeyRef:
                name: "backend-config-port"
                key: PORT

           - name: "MYDATABASE"
             valueFrom:
              secretKeyRef:
                name: "backend-secrets-canary-stable"
                key: MYDATABASE

               
