apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: portfolio-staging
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: "backend=harshvrm10/production-grade-pipeline-images,frontend=harshvrm10/production-grade-pipeline-images"

    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build

    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^backend-v.*
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^frontend-v.*

    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.stable.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.stable.image.tag

    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.stable.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.stable.image.tag

spec:
  project: default

  source:
    repoURL: https://github.com/vrmharsh/Production-Grade-DevSecOps-Platform.git
    targetRevision: main
    path: helm/portfolio-app/portfolio-app

    helm:
      valueFiles:
        - ../../../environments/staging/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: stage-canary

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true