[FILTER]
      Name                  kubernetes
      Match                 kube.*
      Kube_Tag_Prefix       kube.
      Kube_URL              https://kubernetes.default.svc:443
      Merge_Log             On
      Keep_Log              Off
      K8S-Logging.Parser    On
      K8S-Logging.Exclude   Off

#Fluent bit uses this kube_URL to talk with k8 api server, this is not accessible from the lcoal browser since this is used by fluent bit internally to access api server