# master fluent-bit config file

[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parser.conf

@include input.conf
@include filter.conf
@include output.conf

