[INPUT]
    Name              tail
    Path              /var/log/containers/*.log
    Parser            cri
    Tag               kube.var.log.containers.*
    Refresh_Interval  5
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On
    DB                /var/log/flb_kube.db

    Ignore_Older      1h
    Rotate_Wait       30


#Parser cri because container runtime genereates the cri formatted logs
#DB flb_kube.db is the local sqlite file which stores every read made by fluent-bit so that re-read of the logs does not occur.
