apiVersion: v1

kind: Service

metadata:
  name: "frontend-stable-service"
  namespace: "stage-canary"

spec:

  selector:
    app: "frontend-stable-label"

  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
   

  type: ClusterIP 