apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater

metadata:
  name: portfolio-staging
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: portfolio-staging
      useAnnotations: true