helm:
  parameters:
  - name: backend.stable.image.repository
    value: harshvrm10/production-grade-pipeline-images
    forcestring: true
  - name: backend.stable.image.tag
    value: backend-v38
    forcestring: true
  - name: frontend.stable.image.repository
    value: harshvrm10/production-grade-pipeline-images
    forcestring: true
  - name: frontend.stable.image.tag
    value: frontend-v38
    forcestring: true
