apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
type: Opaque
stringData:
  critical-slack: <CRITICAL_SLACK_WEBHOOK>
  warning-slack: <WARNING_SLACK_WEBHOOK>
  info-slack: <INFO_SLACK_WEBHOOK>