apiVersion: v1

kind: Service

metadata:
  name: "manual-kube-state-metrics-service"
  namespace: "prod-blue-green"

spec:
   
  selector:
    app: "manual-kube-state-metrics-label"

  ports:
  - protocol: TCP
    port:  80
    targetPort: 8080


  type: ClusterIP
    
