apiVersion: v1

kind: Service

metadata:
  name: "manual-node-exporter-service"
  namespace: "prod-blue-green"

spec:
   
  selector:
    app: "manual-node-exporter-label"

  ports:
  - protocol: TCP
    port:  80
    targetPort: 9100

  type: ClusterIP
    
