{{- if eq .Values.deploymentStrategy "blueGreen" }}

apiVersion: apps/v1

kind: Deployment

metadata:
   name: "frontend-green-deployment"
   namespace: {{ .Values.namespace }}
   labels: 
     app: frontend-green-deployment-label

spec:
   
   replicas: {{ .Values.frontend.green.replicaCount }}    

   selector: 
     matchLabels:
       app: frontend-green-deployment-label
       version: green

   template:

     metadata:
       labels: 
         app: frontend-green-deployment-label
         version: green

     spec:
       containers:
       - name: "frontend-green-container"
         image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.green.imageTag }}"
         ports: 
          - containerPort: 3000
         resources:
          requests:
           cpu: "200m"
           memory: "512Mi"

          limits:
           cpu: "400m"
           memory: "1Gi"

         readinessProbe:
           httpGet:
             path: /
             port: 3000
           initialDelaySeconds: 30
           periodSeconds: 10
            
           timeoutSeconds: 5 
           successThreshold: 1
           failureThreshold: 5

         livenessProbe:
           httpGet:
             path: /
             port: 3000
           initialDelaySeconds: 45
           periodSeconds: 20
            
           timeoutSeconds: 5 
           failureThreshold: 5
        
{{- end }}