name: CI pipelines

# below means only run if the target branch is main.
on:
 pull_request:
  branches:
   - main
 push:
  branches:
   - main

# two jobs mens parallel jobs so over all pipeline is faster.
jobs:
 frontend-build-and-test:
#  runs-on: ubuntu-latest   # Full Ubuntu VM (currently maps to ubuntu-22.04)
   runs-on: 
    - self-hosted
    - devsecops

   steps:
# a vm is created when pipeline is triggered 
# and it is empty, so first step is that it needs the do git clone repository which is handled by checkout stage.   
   - name: Checkout Code
     uses: actions/checkout@v4

   - name: setup node js
     uses: actions/setup-node@v4
     with: 
      node-version: 18
      cache: npm
      cache-dependency-path: frontend/package-lock.json

# the above method is automatic because here git-hub manages the things.

   - name: install frontend dependencies
     working-directory: frontend
     run: npm ci #npm install
# npm ci is faster, removed the previous installed dpendencies, faster, make sure to download the dpendencies that matches exaclty the code for example node version 18 which currently the application is written in.
   
   - name: build frontend application
     working-directory: frontend
     run: npm run build
    
#   - name: run frontend tests
#     run: npm test
   
   - name: package the frontend build
     run: |
       tar -czf frontend-build.tar.gz frontend/build

   - name: upload the frontend artifacts
     uses: actions/upload-artifact@v6
     with:
       name: frontend-build
       path: frontend-build.tar.gz


 backend-build-and-test:
#  runs-on: ubuntu-latest 
  runs-on:
   - self-hosted
   - devsecops
  
  steps:
   - name: checkout code
     uses: actions/checkout@v4

   - name: setup backend node js
     uses: actions/setup-node@v4
     with: 
      node-version: 18
      cache: npm
      cache-dependency-path: backend/package-lock.json
  
   - name: install backend dependencies
     working-directory: backend
     run: npm ci #npm install

#   - name: run backend test
#     run: npm run test
   
   - name: package the backend build
     run: |
       tar \
        --exclude='backend/node_modules' \
        -czf backend-build.tar.gz backend

   - name: upload the backend artifacts
     uses: actions/upload-artifact@v6
     with:
      name: backend-build
      path: backend-build.tar.gz

 sonarqube:
  name: static code analysis
  
  runs-on:
   - self-hosted
   - devsecops
  
  needs:
   - frontend-build-and-test
   - backend-build-and-test

  steps:
   - name: code checkout stage
     uses: actions/checkout@v6
   
   - name: debug sonarqube connectivity
     env: 
      SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
     run: | 
       echo 'host url is $SONAR_HOST_URL'
       curl -v $SONAR_HOST_URL/api/system/status

   - name: sonarqube scanning
     uses: SonarSource/sonarqube-scan-action@v6
     env: 
      SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
   
  
  
 semgrep:
  name: SAST

  runs-on:
   - self-hosted
   - devsecops

  needs:
   - frontend-build-and-test
   - backend-build-and-test

  permissions:
    security-events: write
    actions: read
    contents: read

  steps:
   - name: code checkout
     uses: actions/checkout@v4

   - name: semgrep verification
     run: semgrep --version

   - name: semgrep scanning
     run: | 
      semgrep scan --config auto \
      --sarif \
      --output semgrep.sarif .

   - name: SARIF Upload
     uses: github/codeql-action/upload-sarif@v3
     with: 
       sarif_file: semgrep.sarif

# below has been commented because semgrep cloud account is not used over here. But Semgrep OSS and SARIF report generated and given to git-hub security for the analysis.
#     env:
#      semgrep_host_url: ${{secrets.semgrep_host_url}}
#      semgrep_host_token: ${{secrets.semgrep_host_token}}
     


# push artifacts to nexus
  
 nexus:
  name: artifacts

  runs-on:
   - self-hosted
   - devsecops
   
  needs:
   - sonarqube
   - semgrep

  steps:
   - name: code checkout
     uses: actions/checkout@v6

   - name: download the frontend artifacts from git hub
     uses: actions/download-artifact@v6
     with: 
       name: frontend-build
       path: artifacts/frontend

   - name: download the backend artifacts from git hub
     uses: actions/download-artifact@v6
     with: 
       name: backend-build
       path: artifacts/backend
   
   - name: verify the download file
     run: | 
      pwd 
      ls -lh

   - name: upload frontend artifacts to nexus
     env:
      NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
      NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
      NEXUS_URL: ${{secrets.NEXUS_URL}}

     run: | 
       curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
         --upload-file artifacts/frontend/frontend-build.tar.gz \
         "$NEXUS_URL/repository/devsecops-artifacts/frontend-build.tar.gz"
       
   - name: upload backend artifacts to nexus
     env:
       NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
       NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
       NEXUS_URL: ${{secrets.NEXUS_URL}} 

     run: | 
       curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
         --upload-file artifacts/backend/backend-build.tar.gz \
         "$NEXUS_URL/repository/devsecops-artifacts/backend-build.tar.gz"

# docker image build

 docker-build: 
   name: docker image build

   runs-on: 
    - self-hosted
    - devsecops

   needs:
    - nexus 

   steps:
    - name: code checkout
      uses: actions/checkout@v6

    - name: download frontend artifacts from nexus
      env:
       NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
       NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
       NEXUS_URL: ${{secrets.NEXUS_URL}}

      run: | 
       curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
       -O "$NEXUS_URL/repository/devsecops-artifacts/frontend-build.tar.gz"
        
    - name: download backend artifacts from nexus
      env:
       NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
       NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
       NEXUS_URL: ${{secrets.NEXUS_URL}}

      run: | 
       curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
       -O "$NEXUS_URL/repository/devsecops-artifacts/backend-build.tar.gz"   

    - name: unzip the frontend artifacts
      run: |
       tar -xzf frontend-build.tar.gz

    - name: unzip the backend artifacts
      run: |
       tar -xzf backend-build.tar.gz
    
    - name: Set image tag
      run: |
       echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

    - name: frontend docker image build
      run: | 
       docker build \
       -t harshvrm10/production-grade-pipeline-images:frontend-${IMAGE_TAG} \
       -f frontend/Dockerfile.artifact .  

    - name: backend docker image build
      run: | 
       docker build \
       -t harshvrm10/production-grade-pipeline-images:backend-${IMAGE_TAG} \
       -f backend/Dockerfile.artifact .   

 trivy-scanning: 
   name: scanning docker images for vulnerability

   runs-on: 
    - self-hosted
    - devsecops

   needs:
    - docker-build

   steps:
    - name: code-checkout
      uses: actions/checkout@v6

    - name: Set Image Tag
      run: |
        echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

    - name: scanning the frontend docker image
      run: | 
       trivy image harshvrm10/production-grade-pipeline-images:frontend-${IMAGE_TAG}

    - name: scanning the backend docker image
      run: |
       trivy image harshvrm10/production-grade-pipeline-images:backend-${IMAGE_TAG}

    - name: generated frontend-trivy SARIF report 
      run: | 
       trivy image \
       --format sarif \
       --output frontend-trivy.sarif \
       harshvrm10/production-grade-pipeline-images:frontend-${IMAGE_TAG}


    - name: generated backend-trivy SARIF report 
      run: | 
       trivy image \
       --format sarif \
       --output backend-trivy.sarif \
       harshvrm10/production-grade-pipeline-images:backend-${IMAGE_TAG}

    - name: upload frontend-trivy SARIF report to git
      uses: github/codeql-action/upload-sarif@v4
      with: 
        sarif_file: frontend-trivy.sarif
        category: frontend-trivy

    - name: upload backend-trivy SARIF report to git
      uses: github/codeql-action/upload-sarif@v4
      with: 
        sarif_file: backend-trivy.sarif
        category: backend-trivy



 docker-image-push:
  
  runs-on:
   - self-hosted
   - devsecops

  needs:
   - trivy-scanning

  steps: 
   - name: code-checkout
     uses: actions/checkout@v6
   
   - name: Set Image Tag
     run: |
       echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

   - name: docker login
     env: 
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

     run: |
      echo "$DOCKER_PASSWORD" | docker login \
      -u "$DOCKER_USERNAME" \
      --password-stdin

   - name: frontend-image-push  
     run: |
      docker push harshvrm10/production-grade-pipeline-images:frontend-${IMAGE_TAG}

   - name: backend-image-push  
     run: |
      docker push harshvrm10/production-grade-pipeline-images:backend-${IMAGE_TAG}

#CI is completed.

#CD is below:

 verify-image-updater:
 
  continue-on-error: true

  runs-on:
    - self-hosted
    - devsecops

  needs:
    - docker-image-push

  steps:
    - name: Checkout GitOps Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Debug repository structure
      run: |
        echo "Current directory:"
        pwd

        echo ""
        echo "Repository root:"
        ls -la

        echo ""
        echo "Finding all values.yaml files..."
        find . -name values.yaml

    - name: Wait for Image Updater to update GitOps Repository
      shell: bash
      run: |

        FRONTEND_EXPECTED_TAG="frontend-v${{ github.run_number }}"
        BACKEND_EXPECTED_TAG="backend-v${{ github.run_number }}"

        echo "Waiting for Argo CD Image Updater..."
        echo "Expected Frontend Tag : $FRONTEND_EXPECTED_TAG"
        echo "Expected Backend Tag  : $BACKEND_EXPECTED_TAG"

        for i in {1..30}; do

          git fetch origin main
          git reset --hard origin/main

          FRONTEND_CURRENT_TAG=$(yq -r '.frontend.stable.image.tag' production-grade-gitops/environments/staging/values.yaml)

          BACKEND_CURRENT_TAG=$(yq -r '.backend.stable.image.tag' production-grade-gitops/environments/staging/values.yaml)

          echo ""
          echo "Attempt $i"
          echo "Frontend Current : $FRONTEND_CURRENT_TAG"
          echo "Frontend Expected: $FRONTEND_EXPECTED_TAG"
          echo "Backend Current  : $BACKEND_CURRENT_TAG"
          echo "Backend Expected : $BACKEND_EXPECTED_TAG"

          if [[ "$FRONTEND_CURRENT_TAG" == "$FRONTEND_EXPECTED_TAG" && \
                "$BACKEND_CURRENT_TAG" == "$BACKEND_EXPECTED_TAG" ]]; then

            echo "GitOps repository updated successfully."
            exit 0

          fi

          echo "Image Updater has not updated the repository yet."
          sleep 20

        done

        echo "Timed out waiting for Argo CD Image Updater."
        exit 1


 verify-argocd-sync:

  name: Verify ArgoCD Sync

  runs-on:
    - self-hosted
    - devsecops

  needs:
    - verify-image-updater

  timeout-minutes: 6

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Wait for ArgoCD to Sync
      shell: bash
      run: |

        echo "Waiting for ArgoCD to sync application..."

        for i in {1..30}; do

          SYNC_STATUS=$(kubectl get application portfolio-staging -n argocd -o json | jq -r '.status.sync.status')
          HEALTH_STATUS=$(kubectl get application portfolio-staging -n argocd -o json | jq -r '.status.health.status')

          echo "Sync Status   : $SYNC_STATUS"
          echo "Health Status : $HEALTH_STATUS"

          if [[ "$SYNC_STATUS" == "Synced" && "$HEALTH_STATUS" == "Healthy" ]]; then
            echo "Application synced successfully."
            exit 0
          fi

          echo "Retrying in 10 seconds..."
          sleep 10

        done

        echo "Timed out waiting for ArgoCD Sync."

        kubectl get application portfolio-staging -n argocd -o yaml

        exit 1

 verify-k8s-rollout:

  name: Verify Kubernetes Rollout

  runs-on:
    - self-hosted
    - devsecops

  needs:
    - verify-argocd-sync

  timeout-minutes: 10

  steps:

    - name: Verify Backend Stable Rollout
      run: |
        kubectl rollout status deployment/backend-stable \
          -n stage-canary \
          --timeout=300s

    - name: Verify Backend Canary Rollout
      run: |
        kubectl rollout status deployment/backend-canary \
          -n stage-canary \
          --timeout=300s

    - name: Verify Frontend Stable Rollout
      run: |
        kubectl rollout status deployment/frontend-stable \
          -n stage-canary \
          --timeout=300s

    - name: Verify Frontend Canary Rollout
      run: |
        kubectl rollout status deployment/frontend-canary \
          -n stage-canary \
          --timeout=300s

    - name: Verify Pods
      run: |
        kubectl get pods -n stage-canary -o wide

    - name: Verify Deployments
      run: |
        kubectl get deployments -n stage-canary

    - name: Verify Services
      run: |
        kubectl get svc -n stage-canary

 